Checkin/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from signin.views import quiz_guess

urlpatterns = patterns('',
   # Example:
   # (r'^sec/', include('sec.foo.urls')),

   # Uncomment the admin/doc line below to enable admin documentation:
   #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

   # Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),

	(r'^stats/', 'stats.views.index'),
	(r'^$', 'signin.views.index'),
	(r'^signin/', 'signin.views.signin'),
	(r'^new/', 'signin.views.createNewRecord'),
    (r'^updatemembership/', 'signin.views.updateMembership'),
	(r'^addadvertisingmethod/(?P<trimmed_idnum>\d+)/$', 'signin.views.addAdvertisingmethod'),
	(r'^createadvertisingmethod/$', 'signin.views.createNewAdvertisingmethod'),# Process a quiz guess
    (r'^test/(?P<pid>\w+)/$', 'signin.views.quiz_guess'),
    (r'^emailfinder/$', 'signin.views.addEmails')
    #(r'^django-csvimport/', include('excel.urls')),
)

Checkin/signin/models.py
from django.db import models
from django.utils import timezone
import datetime

class Event(models.Model):
	date = models.DateField()	
	id = models.AutoField(primary_key=True, db_column='id')

	def __unicode__(self):
		return self.date.__str__()

class ProfessionalEvent(models.Model):
	date = models.DateField()	

	def __unicode__(self):
		return self.date.__str__()

class Advertisingmethod(models.Model):
	name = models.CharField(max_length = 30)	
	def __unicode__(self):
		return self.name


class Member(models.Model):
	idnum = models.CharField(max_length = 20, default='')
	pid = models.CharField(max_length = 20, default='')
	firstname = models.CharField(max_length = 20, default='')
	lastname = models.CharField(max_length = 20, default='')
	email = models.CharField(max_length = 20, default='')
	first_event_date = models.DateTimeField(verbose_name='First event attended', default=datetime.date.today())
	membership_expiration_date = models.DateTimeField(verbose_name='Membership expiration date', default=datetime.date.today())
	studenttype = models.CharField(max_length = 20, default='')
	membershipexpiration = models.CharField(max_length = 20, default='') 
	advertisingmethod = models.CharField(max_length = 200, default='')#models.ForeignKey(Advertisingmethod, default='')
	referername = models.CharField(max_length = 20, default='')
	paymentinfo = models.CharField(max_length = 20, default='')
	event1_22_11 = models.CharField(max_length = 20, default='')
	event9_8_11 = models.CharField(max_length = 20, default='')
	event9_10_11 = models.CharField(max_length = 20, default='')
	event9_15_11 = models.CharField(max_length = 20, default='')
	event9_29_11 = models.CharField(max_length = 20, default='')
	event10_6_11 = models.CharField(max_length = 20, default='')
	event10_13_11 = models.CharField(max_length = 20, default='')
	eventsocial10_15= models.CharField(max_length = 20, default='')
	event10_20_11 = models.CharField(max_length = 20, default='')
	event10_27_11 = models.CharField(max_length = 20, default='')
	event11_3_11 = models.CharField(max_length = 20, default='')
	event11_10_11 = models.CharField(max_length = 20, default='')
	event12_1_11 = models.CharField(max_length = 20, default='')
	event1_19_2012 = models.CharField(max_length = 20, default='')
	event1_26_2012 = models.CharField(max_length = 20, default='')
	event2_2_2012 = models.CharField(max_length = 20, default='')
	eventSocial2_4_2012 = models.CharField(max_length = 20, default='')
	event2_9_2012 = models.CharField(max_length = 20, default='')
	def __unicode__(self):
		return self.pid
	def statsID(self):
		if self.idnum != "":
			idstatus = "(has id)"
		else:
			idstatus = "(no id)"
		return self.lastname + ", " + self.firstname + " " + idstatus
	
	def process_membership(self, membership_type):
		if membership_type is None:
			self.membership_expiration_date = datetime.date.today() + datetime.timedelta(days=1)
		elif membership_type == "6 months":
			self.membership_expiration_date = datetime.date.today() + datetime.timedelta(days=6*30)
		elif membership_type == "12 months":
			self.membership_expiration_date = datetime.date.today() + datetime.timedelta(days=12*30)
		else:
			self.membership_expiration_date = datetime.date.today() + datetime.timedelta(days=1)
		self.save()


class Record(models.Model):
	member = models.ForeignKey(Member)
	event = models.ForeignKey(Event)
	def __unicode__(self):
		return self.member.firstname + " " + self.member.lastname + " " + self.event.date.__str__()
	
class ProfessionalRecord(models.Model):
	member = models.ForeignKey(Member)
	professional_event = models.ForeignKey(ProfessionalEvent)
	def __unicode__(self):
		return self.member.firstname + " " + self.member.lastname + " " + self.professional_event.date.__str__()

class MembershipExpiredException(Exception):
	def __init__(self, *args):
		# *args is used to get a list of the parameters passed in
		self.args = [a for a in args]

Checkin/stats/models.py
from django.db import models

# Create your models here.

Checkin/signin/views.py
from Checkin.middleware import *
from datetime import date
from django import forms
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.utils import simplejson
from middleware import Http403, BadUserCreation
from models import *
from utils import addToListserv
import datetime
import hs
import logging

logger = logging.getLogger(__name__)

def header_search():
	cat_values = []
	cats_list = Member.objects.all()
	for cat in cats_list:
		cat_values.append((cat.statsID()))
	return cat_values

def addEmails(args):
	pass
#	noemails = Member.objects.filter(email='')
#	saveCount = emptyHSEmailViaName = tooManyHSMatches = emptyHSEmailViaPID = tooManyHSMatchesViaPID = 0
#	for person in noemails:
#		hsmatches = hs.search(person.firstname + ' ' + person.lastname)
#		if(len(hsmatches) == 1): #only one person, let's see if their email is saved
#			if(hsmatches[0].get('mail') != ''):
#				person.email = hsmatches[0].get('mail')
#				person.save()
#				saveCount += 1
#			else:
#				emptyHSEmailViaName += 1
#		else:
#			tooManyHSMatches += 1
#			hsmatches = hs.search(person.pid)
#			if(len(hsmatches) == 1):
#				if(hsmatches[0].get('mail') != ''):
#					person.email = hsmatches[0].get('mail')
#					person.save()
#					saveCount += 1
#				else:
#					emptyHSEmailViaPID += 1
#			else:
#				tooManyHSMatchesViaPID += 1
						
#			
#	logger.info(str(len(hsmatches)) + ' found for ' + person.firstname + ' ' + person.lastname)
#	logger.info('added emails for ' + str(saveCount) + ' people.')
#	logger.info('Failed for  ' + str(len(noemails) - saveCount) + ' people.')
#	logger.info('Failures: ' + str(emptyHSEmailViaName) + ' empty HS via name emails')
#	logger.info('Failures: ' + str(emptyHSEmailViaPID) + ' empty HS via pid emails')
#	logger.info('          ' + str(tooManyHSMatches) + ' too many hs matches')
#	logger.info('          ' + str(tooManyHSMatchesViaPID) + ' too many hs matches via pid')

def quiz_guess(request, pid):   
	message = {"mail": "", "givenName": ""}
	if request.is_ajax():
		results = hs.search(pid)
		person = results[0]
		logger.info(results)
		message['firstname'] = person.get('givenName')
		message['major'] = person.get('major')
		message['lastname'] = person.get('sn')
		message['email'] = person.get('mail')
		json = simplejson.dumps(message)
	return HttpResponse(json, mimetype='application/json')
	
class SigninForm(forms.Form):
	idnum = forms.CharField()	
	firstname = forms.CharField(required=False)
	lastname = forms.CharField(required=False)
	associate = forms.BooleanField(widget=forms.CheckboxInput, required=False)
	professional_lesson = forms.BooleanField(widget=forms.CheckboxInput, required=False)

class SigninForm2(forms.Form):
	vtpid = forms.CharField()
	firstname = forms.CharField()
	lastname = forms.CharField()
	advertisingmethod = forms.ModelChoiceField(queryset=Advertisingmethod.objects.all())

class AddAdvertisingmethodForm(forms.Form):
	name = forms.CharField()

def index(request):
	return render_to_response('signin.html', {'choices': Member.objects.all()}, context_instance=RequestContext(request))

def getToday():
	return Event.objects.get(date=date.today())

def getTodayProfessionalEvent():
	return ProfessionalEvent.objects.get(date=date.today())

def checkinMember(member, professional_lesson=False):
	try:
		if member.membership_expiration_date is None:
			logger.info("membership expiration none, setting to tomorrow")
			member.process_membership(None)#Today is their free day
		expiration_date = member.membership_expiration_date
		current_date = datetime.date.today()
		if isinstance(expiration_date, datetime.datetime):
			expiration_date = expiration_date.date()
		if expiration_date < current_date:
			exception_string = "Membership expiration date: %s Current date: %s" % (expiration_date, current_date)
			raise MembershipExpiredException(member, exception_string)
#		today = datetime.date.today()
#		if member.membership_expiration_date < today:
#			raise MembershipExpiredException(member, "Membership expiration date: %s Current date: %s" % (member.membership_expiration_date, today))

#		print "exp date: %s now: %s" % (member.membership_expiration_date, today)
#		print "exp date: %s now: %s" % (member.membership_expiration_date, datetime.datetime.now())
		if professional_lesson:
			logger.info('Member attending professional lesson')
			ProfessionalRecord.objects.get_or_create(member=member,professional_event=getTodayProfessionalEvent())
		res = Record.objects.get_or_create(member=member, event=getToday())
		return res[1]
	except MembershipExpiredException:
		logger.error("Re raising membershipexpired")
		raise
	except Record.DoesNotExist:
		raise Http403
	except Event.DoesNotExist:
		raise Http403

def addAdvertisingmethod(request, trimmed_idnum):
	return render_to_response('new_advertisingmethod.html', {'idnum': trimmed_idnum}, context_instance=RequestContext(request))

def createNewAdvertisingmethod(request):
	name = request.POST['name']
	trimmed_idnum = request.POST['idnum']
	if len(Advertisingmethod.objects.filter(name=name)) == 0:
		o = Advertisingmethod(name=name)
		o.save()
	return render_to_response('newrecord.html', {'idnum': trimmed_idnum, 'choices': Advertisingmethod.objects.all(),
															 			 'membershiptypes': ["Single free event", \
																				 			 "6 months", \
																				  			 "12 months"]}, \
							 context_instance=RequestContext(request))

def signin(request):
	if request.method == 'POST': # If the form has been submitted...
		form = SigninForm(request.POST) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			logger.info('form valid')
			idnum = form.cleaned_data['idnum']
			firstname = form.cleaned_data['firstname']
			lastname = form.cleaned_data['lastname']
			needToAssociate = form.cleaned_data['associate']
			professional_lesson = form.cleaned_data['professional_lesson']
			if needToAssociate:
				logger.info('Need to associate ID with existing member')
				matches = Member.objects.filter(firstname__iexact=form.cleaned_data['firstname'], lastname__iexact=form.cleaned_data['lastname'])
				logger.info('Finding matches for member ' + str(form.cleaned_data['firstname']) + ' ' + str(form.cleaned_data['lastname']))
				if len(matches) == 1: #all is well, make the id association
					logger.info('Found a match, storing ID')
					matches[0].idnum = idnum
					matches[0].save()
					logger.info('Saved id, returning to home page')
					return render_to_response('idassociator.html', {})
				elif int(len(matches)) > int(1):
					logger.info('Found too many matches, need to fix')
				else:
					logger.info('Found no matches, need to make new member.')
			else:
				logger.info('Looking up existing member for ID')
				matches = Member.objects.filter(idnum=idnum)
				logger.info('signin request for ' + str(idnum) + ' matched ' + str(len(matches)) + ' members in database')
			if len(matches) == 1:
					# Member already exists, add attendance record
					try:
						if checkinMember(matches[0], professional_lesson=professional_lesson):
							logger.info("member successfully signed in")
							return render_to_response('signin_success.html', {'': ''}, context_instance=RequestContext(request))
						else:
							logger.info('duplicate signin')
							return render_to_response('signin_duplicate.html', {'': ''}, context_instance=RequestContext(request))
					except MembershipExpiredException, e:
						logger.exception(e)
						return render_to_response('membership_expired.html', {'idnum':idnum,\
																			  'membershiptypes': ["6 months", \
                                                                                                  "12 months"]}, \
                                                   context_instance=RequestContext(request))
					except:
						raise
			else:
				return render_to_response('newrecord.html', {'idnum': idnum, \
															 'professional_lesson' : professional_lesson,\
															 'choices': Advertisingmethod.objects.all(),
															 'membershiptypes': ["Single free event", \
                                                                                 "6 months", \
																				  "12 months"]}, \
										 context_instance=RequestContext(request))
		else:
					return render_to_response('newrecord.html', {'idnum': idnum, \
																'choices': Advertisingmethod.objects.all(),\
																'professional_lesson' : professional_lesson,\
																'membershiptypes': ["Single free event", \
                                                                                 "6 months", \
																				  "12 months"]}\
											, context_instance=RequestContext(request))
	else:
			form = SigninForm() # An unbound form
			return render_to_response('signin.html', {'form': form, 'choices' : Member.objects.all() }, context_instance=RequestContext(request))


def createNewRecord(request):
	# Create a new record, add attendance record
	try:
		m = Member(idnum=request.POST['idnum'], pid=request.POST['pid'], firstname=request.POST['firstname'], lastname=request.POST['lastname'], advertisingmethod=get_object_or_404(Advertisingmethod, name=request.POST['advertisingmethod']))
		membership_type = request.POST['membershiptype']
		m.process_membership(membership_type)
		m.save()
		addToListserv(request.POST['email'], request.POST['firstname'], request.POST['lastname'])
		checkinMember(m, request.POST['professional_lesson'])
	except Event.DoesNotExist:
		logger.error('Event does not exist, cannot make user')		
		raise BadUserCreation
	return render_to_response('signin_success.html', {'': ''}, context_instance=RequestContext(request))

def updateMembership(request):
	try:            
		membership_type = request.POST['membershiptype']
		idnum = request.POST['idnum']
		logger.info('updating membership information for %s with length of %s' % (idnum, membership_type))

Checkin/stats/views.py
from Checkin.signin.models import Record, Member, Event, Advertisingmethod
from django.shortcuts import render_to_response
from django.template import RequestContext
from signin.models import *

def index(request):
	records = Record.objects.all()
	
	attend_member = {}
	attend_advertisingmethod = {}
	
	for member in Member.objects.all():
		attend_member[member.statsID] = []
		attend_member[member.statsID].append(member.firstname + " " + member.lastname)
		try:
			attend_member[member.statsID].append(member.advertisingmethod.name)
		except:
			attend_member[member.statsID].append(member.advertisingmethod)
		attend_member[member.statsID].append([])
		for g in Event.objects.all():
			try:
				record = Record.objects.get(member=member, event=g)
				attend_member[member.statsID][2].append(1)
			except:		
				attend_member[member.statsID][2].append(0)
		attend_member[member.statsID].append(100 * sum(attend_member[member.statsID][2])/len(attend_member[member.statsID][2]))

	for s in Advertisingmethod.objects.all():
		if s.name == 'Individual':
			continue;
		attend_advertisingmethod[s.name] = []
		attend_advertisingmethod[s.name].append(s.name)
		attend_advertisingmethod[s.name].append([])
		for g in Event.objects.all():
			ok = 0
			for member in Member.objects.all():
				try:
					record = Record.objects.get(member=member, event=g)
					if record.member.advertisingmethod == s:
						ok = 1
				except:
					ok = ok
			attend_advertisingmethod[s.name][1].append(ok)

		attend_advertisingmethod[s.name].append(100 * sum(attend_advertisingmethod[s.name][1])/len(attend_advertisingmethod[s.name][1]))
	
	return render_to_response('stats.html', {'event': Event.objects.all(), 'attend': attend_member, 'attend2': attend_advertisingmethod}, context_instance=RequestContext(request))

Checkin/templates/BadUserCreation.html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
        <meta charset="UTF-8">
        <title>Try again!</title>
</head>
<body>
    <p>Failed to create user.  Maybe you had a bad ID#, first name, or last name.  Go back and try again.</p>
</body>
</html>

Checkin/templates/idassociator.html
<html>
<head>
<script type="text/javascript">
function redirect() {
	window.location = "http://0.0.0.0:8081/
}
</script>
</head>
<body onLoad="setTimeout('redirect()', 1000)">
	<center>
	<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
	<h2>ID associated successfully, please sign in</h2>	
	</center>
</body>
<a href="/">Home</a>
</html>

Checkin/templates/membership_expired.html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
        <meta charset="UTF-8">
        <title>Try again!</title>
</head>
<body>
	<div id="content">
		<form action="/updatemembership/" method="post"> {% csrf_token %}
		    <p>Membership expired!  Please become a member or renew your membership.</p>
			<strong>Membership type: </strong>
			<select name="membershiptype">
			{% for membershiptype in membershiptypes %}
				<option value="{{ membershiptype }}">{{ membershiptype }}</option>
			{% endfor %}
			</select>
			<input type="hidden" name="idnum" value="{{ idnum }}">
			<input type="submit" value="Submit" />
		</form>
		<a href="/">Home</a>
	</div>
</body>
</html>

Checkin/templates/new_advertisingmethod.html
<html>
<head>
<style type="text/css">
#content {
	font-family: Arial;
}
</style>
</head>
<body>
<div id="content">
	<form action="/createadvertisingmethod/" method="post"> {% csrf_token %}
		<center>
	
		<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
		<h2>How did you hear about us?</h2>

		<input type="text" name="name"><br><br>

		<input type="hidden" name="idnum" value="{{ idnum }}">
		<input type="submit" value="Submit"/>	
		<h3><i>Note: You must re-enter your information when you return to the signin page.  Sorry for the inconvienence</i></h3>
		</center>
	</form>

</div>
</body>
</html>

Checkin/templates/newrecord.html
<html>
<head>
<script type="text/javascript"
 src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js">
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#pid').bind('blur', function () {
      $.get("/test/"+this.value+"/", function(data) {
          console.log("get called");
          if(data){
          	console.log("had data");
          	if(data.firstname){
          		console.log("had first name");
          		$("#firstname").val(data.firstname);
          	}if(data.lastname){
          		console.log("had last name");
          		$("#lastname").val(data.lastname);
            }if(data.major){
          		console.log("had major");
          		$("#major").val(data.major);
            }if(data.email){
          		console.log("had email");
          		$("#email").val(data.email);
            }
          }
      });
   });
});
</script>
<style type="text/css">
#content {
	font-family: Arial;
}
</style>
</head>
<body>
<div id="content">
	<form action="/new/" method="post"> {% csrf_token %}
		<center>
	
		<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
		<h2>Enter your information:</h2>

		<strong>VT PID (without @vt.edu): </strong><input type="text" name="pid" id="pid"><br><br>
		<strong>First Name: </strong><input type="text" name="firstname" id="firstname"><br>
		<strong>Last Name: </strong><input type="text" name="lastname" id="lastname"><br>
		<strong>Email: </strong><input type="text" name="email" id="email"><br>
		<strong>Major: </strong><input type="text" name="major" id="major"><br>
		
	
		<strong>Membership type: </strong>
		<select name="membershiptype">
		{% for membershiptype in membershiptypes %}
			<option value="{{ membershiptype }}">{{ membershiptype }}</option>
		{% endfor %}
		</select>
		<br>
		<strong>How you heard about us: </strong>
		<select name="advertisingmethod">
		{% for choice in choices %}
			<option value="{{ choice.name }}">{{ choice.name }}</option>
		{% endfor %}
		</select>
		<a href="/addadvertisingmethod/{{ idnum }}">Add</a>
		<br><br>
		<input type="hidden" name="idnum" value="{{ idnum }}">
		<input type="hidden" name="professional_lesson" value="{{ professional_lesson }}">
		<input type="submit" value="Submit"/>	
		</center>
	</form>
</div>
</body>
</html>

Checkin/templates/signin.html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript"
 src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js">
</script>
<SCRIPT TYPE="text/javascript">
// copyright 1999 Idocs, Inc. http://www.idocs.com
// Distribute this script freely but keep this notice in place
function numbersonly(myfield, e, dec)
{
var key;
var keychar;

if (window.event)
   key = window.event.keyCode;
else if (e)
   key = e.which;
else
   return true;
keychar = String.fromCharCode(key);

// control keys
if ((key==null) || (key==0) || (key==8) || 
    (key==9) || (key==27) )
   return true;

if(key == 13)
          return false;


// numbers
else if ((("0123456789").indexOf(keychar) > -1))
   return true;

// decimal point jump
else if (dec && (keychar == "."))
   {
   myfield.form.elements[dec].focus();
   return false;
   }
else
   return false;
}
//-->
</SCRIPT>
/*<script type="text/javascript">
  $(document).ready(function() {
    $('#id_idnum').bind('blur', function () {
      $.get("/emailfinder/", function(data) {
          console.log("get called");
      });
   });
});
</script>
<style type="text/css">
#content {
	font-family: Arial;
}
</style>
</head>
<body OnLoad="document.form.idnum.focus();">
<center>
<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
<br>
<h2>Please swipe your hokie passport (or enter phone number if not a student)</h2>
<div id="content">
	<form action="/signin/" method="post" name="form"> {% csrf_token %}
		<p><label for="id_idnum"></label>
		<input type="password" name="idnum" id="id_idnum"  maxlength="9"
		style="height: 32pt; font-size: 24pt; width: 400px; text-align: center"
		onkeypress="return numbersonly(this,event)"  /></p>
		
		<p><label for="id_professional_lesson">Professional Lesson</label>
    	<input type="checkbox" name="professional_lesson" id="id_professional_lesson" /></p>
		
		<p><label for="id_firstname"></label>
		<input type="text" name="firstname" id="id_firstname"
		value="First name" disabled="disabled"
		 onblur="if (this.value == '') {this.value = 'First name';}"
 		 onfocus="if (this.value == 'First name') {this.value = '';}"/></p>
		
		<p><label for="id_lastname"></label>
		<input type="text" name="lastname" id="id_lastname" value="Last name" disabled="disabled"
		 onblur="if (this.value === '') {this.value = 'Last name';}"
 		 onfocus="if (this.value === 'Last name') {this.value = '';}"/></p>		
		
		<p><label for="id_associate">Associate ID with existing member (only do this once per member!)</label>
		<input type="checkbox" name="associate" id="id_associate" 
    	onclick="if(this.checked){
    	 			id_lastname.disabled='';
    	 			id_firstname.disabled='';
    	 		 }else{
    	 		 	id_lastname.disabled='disabled';
    	 		 	id_firstname.disabled='disabled';
    	 		 }"
    	/></p>
    	
		<select name="choices">
		{% for choice in choices %}
			<option value="{{ choice.statsID }}">{{ choice.statsID }}</option>
		{% endfor %}
		</select>
		</ul>
		
    	
		<input type="submit" value="Submit" />
		<br>
		<a href="/stats/">Stats</a>
		<br>
		<a href="/admin/">Admin</a>
		</center>
	</form>
</div>
</body>
</html>

Checkin/templates/signin_duplicate.html
<html>
<head>
<script type="text/javascript">
function redirect() {
	// var foo = 1;
	// window.location = "http://0.0.0.0:8000/";
	document.location.href = "/";
}
</script>
</head>
<body onLoad="setTimeout('redirect()', 1000)">
	<center>
	<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
	<h2>You have already signed in today!</h2>	
	</center>
</body>
</html>

Checkin/templates/signin_success.html
<html>
<head>
<script type="text/javascript">
function redirect() {
	document.location.href="/";
	//window.location = "http://0.0.0.0:8000/
	// window.location = "http://172.24.6.174:8000/"
}
</script>
</head>
<body onLoad="setTimeout('redirect()', 1000)">
	<center>
	<h1>Ballroom Dance @ Virginia Tech Attendance</h1>
	<h2>Check-in Successful!</h2>
	<h3>If this was your free lesson, remember that you must pay dues next time.</h3>
	</center>
</body>
<a href="/">Home</a>
</html>

Checkin/templates/stats.html
<html>
<head>
</head>
<style type="text/css">
#content {
	font-family: Arial;
}
td.green {
	background-color: lime;
}
td.red {
	background-color: red;
}
</style>
<body>
<div class="content">
<h1>Membership statistics</h1>
<h2>Individual Members</h2>
<table border="2" width="50%">
	<tr>
		<td width="150"><strong>Member</strong></td>
		<td width="150"><strong>Advertising Method</strong></td>
		{% for g in event %}
		<td width="100"><strong>{{ g.date }}</strong></td>
		{% endfor %}
		<td><strong>Percent</strong></td>
	</tr>
	{% for item in attend.items %}
	<tr>
		<td>{{ item.1.0 }}</td>
		<td>{{ item.1.1 }}</td>

		{% for x in item.1.2 %}
			{% if x == 1 %}
			<td class="green"></td>
			{% else %}
			<td class="red"></td>
			{% endif %}
		{% endfor %}
		<td>{{ item.1.3 }}%</td>
	</tr>
	{% endfor %}
</table>
<h2>Advertising methods</h2>
<table border="2" width="50%">
	<tr>
		<td width="305"><strong>Advertising method</strong></td>
		{% for g in event %}
		<td width="100"><strong>{{ g.date }}</strong></td>
		{% endfor %}
		<td><strong>Percent</strong></td>
	</tr>
	{% for item in attend2.items %}
	<tr>
		<td>{{ item.1.0 }}</td>

		{% for x in item.1.1 %}
			{% if x == 1 %}
			<td class="green"></td>
			{% else %}
			<td class="red"></td>
			{% endif %}
		{% endfor %}
		{% if item.1.2 >= 66 %}
			<td class="green">{{ item.1.2 }}%</td>
		{% else %}
			<td class="red">{{ item.1.2 }}%</td>
		{% endif %}
	</tr>
	{% endfor %}
</table>
</div>
</body>
</html>